[package]
name = "example-completion"
version = "0.1.0"
edition = "2024"

[dependencies.mingling]
path = "../../mingling"

features = [
    # Enable `comp` features
    "comp",
    "parser",
]

[build-dependencies.mingling]
path = "../../mingling"

features = [
    # Enable `comp` features
    "comp",

    # If you want to build completion scripts,
    # enable `builds` features
    "builds",
]

[workspace]
