[example]
id = "example-completion"
name = "Completion"
icon = "🔄"
category = "ux"
desc = """
Demonstrates how to implement dynamic shell completion with `#[completion]` and generate scripts for bash, zsh, fish, and pwsh.
"""
tags = ["comp"]
files = ["src/main.rs", "Cargo.toml"]
