[example]
id = "example-help"
name = "Help"
icon = "💡"
category = "ux"
desc = """
Shows how to use the `#[help]` attribute to provide custom per-command help text that activates when the user passes `--help`.
"""
tags = ["#[help]"]
files = ["src/main.rs", "Cargo.toml"]
