[package]
name = "test-all"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
mingling = { path = "../../../mingling", features = [
    "structural_renderer_full",
    "comp",
    "repl",
    "dispatch_tree",
    "picker",
] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
