use crate::{ProgramCollect, debug, metadata::Description, this, trace};

use std::collections::BTreeSet;
use std::fmt::Display;

mod comp_ctx;
mod flags;
mod shell_ctx;
mod suggest;

#[doc(hidden)]
pub use flags::*;

#[doc(hidden)]
pub use shell_ctx::*;

#[doc(hidden)]
pub use suggest::*;

/// Constant defining the name of the completion subcommand.
///
/// When a user invokes this subcommand (e.g., `your_program __comp`), the
/// program enters completion mode and generates shell completions based on
/// the current shell context.
///
/// This value is used internally by the completion system to intercept the
/// command-line input and redirect to the completion handler.
///
/// ```
/// # #[cfg(feature = "comp")] {
/// # use mingling_core::COMPLETION_SUBCOMMAND;
/// assert_eq!("__comp", COMPLETION_SUBCOMMAND);
/// # }
/// ```
pub const COMPLETION_SUBCOMMAND: &str = "__comp";

#[cfg(feature = "debug")]
use crate::debug::init_env_logger;

#[cfg(not(feature = "dispatch_tree"))]
use crate::ChainProcess;

#[cfg(not(feature = "dispatch_tree"))]
use crate::exec::match_user_input;

/// Mingling Completion Entry Point
///
/// Defines the custom completion logic entry point for the program's shell
/// completion system.
///
/// When a specific command node is matched, the `comp` method is called to
/// generate completion suggestions based on the current shell context. Types
/// implementing this trait are usually automatically generated by the
/// [`dispatcher!`](https://docs.rs/mingling/latest/mingling/macros/macro.dispatcher.html)
/// macro; users typically do not need to implement this trait manually.
///
/// # Manual impl
///
/// If you need to implement it manually, follow the example below:
///
/// ```
/// # #[cfg(feature = "comp")] {
/// # use mingling_core::{Completion, CompletionHelper, ShellContext, Suggest};
/// struct GreetCompletion;
/// struct EntryGreet;
///
/// impl Completion for GreetCompletion {
///     type Previous = EntryGreet;
///
///     fn comp(ctx: &ShellContext) -> Suggest {
///         // Generate completion suggestions based on the shell context
/// # Suggest::FileCompletion
///     }
/// }
/// # }
/// ```
pub trait Completion {
    /// The previous type bound to this entry in the completion chain.
    ///
    /// It is usually the first type generated by
    /// [`Dispatcher`](https://docs.rs/mingling/latest/mingling/trait.Dispatcher.html).
    type Previous;

    /// Generates completion suggestions based on the current shell context.
    ///
    /// This method is called when the completion system needs to provide
    /// custom suggestions for the current command or arguments. Implementors
    /// should decide what to suggest based on the provided [`ShellContext`].
    ///
    /// # Parameters
    ///
    /// * `ctx` — The current shell context information, including the command
    ///   line content, cursor position, current word, previous word, etc.,
    ///   used to determine what should be completed.
    ///
    /// # Returns
    ///
    /// Returns a [`Suggest`] enum value, which can be:
    /// - [`Suggest::Suggest`] carrying a set of candidate suggestion items
    ///   (`BTreeSet<SuggestItem>`), where each item may include a description.
    /// - [`Suggest::FileCompletion`] instructs the shell to fall back to
    ///   filesystem completion.
    fn comp(ctx: &ShellContext) -> Suggest;
}

/// Trait for extracting user input arguments for completion.
///
/// When the `feat comp` feature is enabled, the `dispatcher!` macro will
/// automatically implement this trait for `Entry` types to extract the
/// arguments from user input for completion suggestions.
pub trait CompletionEntry {
    /// Extracts the user input arguments for completion processing.
    ///
    /// This method is called when the completion system needs to retrieve
    /// the raw input arguments from the user's command line. The returned
    /// vector of strings represents the parsed arguments that will be used
    /// to match against the program's command tree and generate completion
    /// suggestions.
    ///
    /// # Returns
    ///
    /// A vector of strings containing the individual arguments from the
    /// user's command-line input.
    fn get_input(self) -> Vec<String>;
}

/// A helper struct for handling command-line completion logic.
///
/// This struct provides static methods for executing completions based on
/// the current shell context and rendering the resulting suggestions in a
/// format appropriate for the target shell.
pub struct CompletionHelper;

impl CompletionHelper {
    /// Executes the completion logic for the given program type (`P`).
    ///
    /// This is the **entry point** of the Mingling Completion system. It converts
    /// the user's shell context (current command line, cursor position, previous
    /// words, etc.) into actual completion suggestions.
    ///
    /// The function first attempts to match the input arguments against the
    /// program's command tree. If a matching dispatcher is found, it delegates to
    /// the program's custom completion logic (`P::do_comp`). If no match is found
    /// or the dispatcher signals "not found", a default completion is used instead,
    /// which provides subcommand suggestions based on the input path.
    ///
    /// # Type Parameters
    ///
    /// * `P` — The top-level program type that implements [`ProgramCollect`], can be
    ///   displayed, compared for equality, and kept alive for the program's lifetime.
    ///
    /// # Returns
    ///
    /// A [`Suggest`] value containing either file completion instructions or a set
    /// of candidate suggestions.
    #[must_use]
    pub fn exec_completion<P>(ctx: &ShellContext) -> Suggest
    where
        P: ProgramCollect<Enum = P> + Display + PartialEq + 'static + std::fmt::Debug,
    {
        #[cfg(feature = "debug")]
        {
            init_env_logger();
            trace_ctx(ctx);
        }

        // Everything before the first argument that matches a command node
        // is treated as global parameters (flags and their values), which do
        // not participate in command tree matching.  The dispatch path starts
        // at that first match, enabling `prog [PARAM]... <subcommand>`
        // style invocations.
        let all_args = ctx.all_words.iter().skip(1).cloned().collect::<Vec<_>>();
        let first_cmd_match = first_command_arg_index::<P>(&all_args);
        let args = first_cmd_match.map_or_else(Vec::new, |start| all_args[start..].to_vec());
        trace!("arguments=\"{}\"", args.join(", "));

        #[cfg(not(feature = "dispatch_tree"))]
        let program = this::<P>();

        #[cfg(not(feature = "dispatch_tree"))]
        let suggest = if let Ok((dispatcher, args)) = match_user_input(program, &args) {
            trace!(
                "dispatcher matched, dispatcher=\"{}\"",
                dispatcher.node().to_string(),
            );
            let begin = dispatcher.begin(args);
            if let crate::ChainProcess::Ok((any, _)) = begin {
                trace!("entry type: {}", any.member_id);
                let result = P::do_comp(&any, ctx);
                trace!("do_comp result: {:?}", result);
                Some(result)
            } else {
                trace!("begin not Ok");
                None
            }
        } else {
            trace!("no dispatcher matched");
            None
        };
        #[cfg(feature = "dispatch_tree")]
        let suggest = if let Ok(any) = P::dispatch_args(&args) {
            debug!("dispatch_args OK, member_id = {:?}", any.member_id);
            trace!("entry type: {}", any.member_id);

            let entry_fallback = <P::EntryFallback as crate::Grouped<P>>::member_id();

            if entry_fallback == any.member_id {
                debug!("entry_fallback matched");
                trace!("begin not Ok");
                None
            } else {
                let result = P::do_comp(&any, ctx);
                debug!("do_comp result: {:?}", result);
                trace!("do_comp result: {:?}", result);
                Some(result)
            }
        } else {
            debug!("dispatch_args failed, args = {:?}", args);
            trace!("no dispatcher matched");
            None
        };

        suggest.map_or_else(
            || {
                if first_cmd_match.is_some() {
                    // A command node has been matched: the global
                    // EntryFallback must not run afterwards, only the
                    // command path is completed.
                    trace!("command node matched, skipping EntryFallback");
                    default_completion::<P>(ctx)
                } else {
                    trace!("using default completion");
                    let fallback = P::do_comp(&P::build_entry_fallback(vec![]), ctx);
                    let default = default_completion::<P>(ctx);
                    match fallback {
                        Suggest::FileCompletion => default,
                        Suggest::Suggest(_) => fallback.combine(default),
                    }
                }
            },
            |custom_suggest| {
                // A concrete entry was dispatched. Merge the entry's own
                // completion with the default subcommand suggestions so that,
                // e.g. `thanks <tab>`, suggests both the leaf nodes (`bob`,
                // `alice`) and the `thanks` entry's own completion.
                trace!("using custom completion: {:?}", &custom_suggest);
                let default = default_completion::<P>(ctx);
                match custom_suggest {
                    Suggest::FileCompletion => {
                        trace!(
                            "custom completion is FileCompletion, using default: {:?}",
                            default
                        );
                        default
                    }
                    Suggest::Suggest(a) => {
                        trace!("combining custom completion with default");
                        match default {
                            Suggest::Suggest(b) => {
                                let mut combined = a;
                                combined.extend(b);
                                Suggest::Suggest(combined)
                            }
                            Suggest::FileCompletion => {
                                // If custom completion has items and default is file
                                // completion, the custom items take priority.
                                Suggest::Suggest(a)
                            }
                        }
                    }
                }
            },
        )
    }

    /// Renders the completion suggestions to standard output.
    ///
    /// This method takes the [`Suggest`] value produced by
    /// [`exec_completion`], and prints the results in a format appropriate for the
    /// user's shell environment.
    ///
    /// - If the suggestion is [`Suggest::FileCompletion`], it prints `"_file_"` and
    ///   exits, instructing the shell to fall back to file completion.
    /// - If the suggestion is [`Suggest::Suggest`] with a set of candidates, it
    ///   formats and prints them according to the shell type (Zsh/PowerShell, Fish,
    ///   or default).
    pub fn render_suggest<P>(ctx: &ShellContext, suggest: Suggest)
    where
        P: ProgramCollect<Enum = P> + Display + 'static,
    {
        trace!("render_suggest called with: {:?}", suggest);
        match suggest {
            Suggest::FileCompletion => {
                trace!("rendering file completion");
                println!("_file_");
                std::process::exit(0);
            }
            Suggest::Suggest(suggestions) => {
                trace!("rendering {} suggestions", suggestions.len());
                match ctx.shell_flag {
                    ShellFlag::Zsh | ShellFlag::Powershell => {
                        trace!("using zsh/pwsh format");
                        print_suggest_with_description(suggestions);
                    }
                    ShellFlag::Fish => {
                        trace!("using fish format");
                        print_suggest_with_description_fish(suggestions);
                    }
                    _ => {
                        trace!("using default format");
                        print_suggest(suggestions);
                    }
                }
            }
        }
    }
}

/// Finds the index of the first argument that matches the head of a
/// registered command node.
///
/// Everything before this index is treated as global parameters (flags and
/// their values), which do not participate in command tree matching.  This
/// allows `prog [PARAM]... <subcommand>` style invocations to resolve the
/// subcommand, while a "broken" path such as `prog -v hello -a someone`
/// still fails to match the `hello someone` node.
fn first_command_arg_index<P>(args: &[String]) -> Option<usize>
where
    P: ProgramCollect<Enum = P> + Display + 'static,
{
    let cmd_heads: Vec<String> = this::<P>()
        .get_nodes()
        .into_iter()
        .filter(|(s, _)| !s.starts_with('_'))
        .map(|(s, _)| s.split(' ').next().unwrap_or("").to_string())
        .collect();

    args.iter().position(|arg| {
        !arg.is_empty() && cmd_heads.iter().any(|head| head.starts_with(arg.as_str()))
    })
}

/// Resolves the `Description` metadata registered for the entry that owns the
/// given (space-separated) command node path, if any.
///
/// The node path is dispatched to obtain the owning entry's member id, and its
/// `Description` is then retrieved via [`ProgramCollect::get_metadata`]. Returns
/// `None` when the path does not resolve to a concrete entry (e.g. an
/// intermediate trie segment that has no entry of its own) or when the entry
/// has no `Description` registered.
fn entry_description<P>(node: &str) -> Option<String>
where
    P: ProgramCollect<Enum = P> + Display + 'static,
{
    let words: Vec<String> = node.split(' ').map(str::to_string).collect();

    #[cfg(feature = "dispatch_tree")]
    let lazy_member = P::dispatch_args(&words).ok().map(|any| any.member_id);

    #[cfg(not(feature = "dispatch_tree"))]
    let lazy_member = match match_user_input(this::<P>(), &words) {
        Ok((dispatcher, args)) => match dispatcher.begin(args) {
            ChainProcess::Ok((any, _)) => Some(any.member_id),
            ChainProcess::Err(_) => None,
        },
        Err(_) => None,
    };

    let member_id = lazy_member?;
    P::get_metadata::<Description>(member_id).map(String::from)
}

/// Builds suggestions from command nodes given an input path.
///
/// Extracted from `default_completion` to keep it under the line-count limit.
fn build_node_suggestions<P>(ctx: &ShellContext, input_path: &[&str]) -> Suggest
where
    P: ProgramCollect<Enum = P> + Display + 'static,
{
    let cmd_nodes: Vec<String> = this::<P>()
        .get_nodes()
        .into_iter()
        .filter(|(s, _)| !s.starts_with('_'))
        .map(|(s, _)| s)
        .collect();

    // Build a suggestion item for `token`, attaching the owning entry's
    // `Description` metadata (resolved via `node_path`) when one is available.
    let make_item = |token: &str, node_path: &str| -> SuggestItem {
        entry_description::<P>(node_path).map_or_else(
            || SuggestItem::new(token.to_string()),
            |desc| SuggestItem::new_with_desc(token.to_string(), desc),
        )
    };

    // Track both the suggestion text and the node path used to look up its
    // description, then deduplicate by suggestion text.
    let mut suggestions: BTreeSet<SuggestItem> = BTreeSet::new();

    // Special case: if input_path is empty, return all first-level commands
    if input_path.is_empty() {
        for node in cmd_nodes {
            let node_parts: Vec<&str> = node.split(' ').collect();
            if let Some(first) = node_parts.first() {
                suggestions.insert(make_item(first, first));
            }
        }
    } else {
        // Get the current word
        let current_word = input_path.last().unwrap();

        // First, handle partial match completion for the current word
        // Only perform current word completion when current_word is not empty
        if input_path.len() == 1 && !ctx.current_word.is_empty() {
            for node in &cmd_nodes {
                let node_parts: Vec<&str> = node.split(' ').collect();
                let Some(first) = node_parts.first() else {
                    continue;
                };
                if first.starts_with(current_word) {
                    suggestions.insert(make_item(first, first));
                }
            }

            // If suggestions for the current word are found, return directly
            if !suggestions.is_empty() {
                return Suggest::Suggest(suggestions);
            }
        }

        // Handle next-level command suggestions
        for node in cmd_nodes {
            let node_parts: Vec<&str> = node.split(' ').collect();

            // If input path is longer than node parts, skip
            if input_path.len() > node_parts.len() {
                continue;
            }

            // Check if input path matches the beginning of node parts
            let mut matches = true;
            for i in 0..input_path.len() {
                if i >= node_parts.len() {
                    matches = false;
                    break;
                }

                if i == input_path.len() - 1 {
                    if !node_parts[i].starts_with(input_path[i]) {
                        matches = false;
                        break;
                    }
                } else if input_path[i] != node_parts[i] {
                    matches = false;
                    break;
                }
            }

            if matches && input_path.len() <= node_parts.len() {
                let last_idx = input_path.len() - 1;
                let is_partial = input_path[last_idx] != node_parts[last_idx];

                // The suggested token and the fully qualified node path that
                // owns it, used to look up its `Description` metadata.
                let (token, owner_path) = if input_path.len() == node_parts.len() {
                    // Completing the final token of this node.
                    (node_parts[last_idx], node_parts.join(" "))
                } else if is_partial {
                    // Completing the current (partial) token in place.
                    (node_parts[last_idx], node_parts[..=last_idx].join(" "))
                } else {
                    // Advancing to the next level under the matched prefix.
                    let idx = input_path.len();
                    (node_parts[idx], node_parts[..=idx].join(" "))
                };

                if input_path.len() == node_parts.len() {
                    if !ctx.current_word.is_empty() {
                        suggestions.insert(make_item(token, &owner_path));
                    }
                } else if input_path.len() < node_parts.len() {
                    suggestions.insert(make_item(token, &owner_path));
                }
            }
        }
    }

    if suggestions.is_empty() {
        file_suggest()
    } else {
        Suggest::Suggest(suggestions)
    }
}

fn default_completion<P>(ctx: &ShellContext) -> Suggest
where
    P: ProgramCollect<Enum = P> + Display + 'static,
{
    debug!("cmd_nodes: {:?}", {
        let nodes: BTreeSet<String> = this::<P>()
            .get_nodes()
            .into_iter()
            .filter(|(s, _)| !s.starts_with('_'))
            .map(|(s, _)| s)
            .collect();
        nodes
    });

    // If the current position is less than 1, do not perform completion
    if ctx.word_index < 1 {
        debug!("word_index < 1, returning file suggestions");
        return file_suggest();
    }

    // Get the current input path
    let input_end = ctx.word_index.min(ctx.all_words.len());

    // Skip global parameters (arguments before the first command node match)
    // when resolving the command path, so `prog [PARAM]... <subcommand>`
    // style invocations suggest the subcommand.
    let input_slice = ctx.all_words.get(1..input_end).unwrap_or(&[]);
    let input_path: Vec<&str> =
        first_command_arg_index::<P>(input_slice).map_or_else(Vec::new, |start| {
            input_slice[start..]
                .iter()
                .map(std::string::String::as_str)
                .collect()
        });
    debug!(
        "input_path={:?}, current_word='{}'",
        input_path, ctx.current_word
    );

    build_node_suggestions::<P>(ctx, &input_path)
}

const fn file_suggest() -> Suggest {
    Suggest::FileCompletion
}

fn print_suggest(suggestions: BTreeSet<SuggestItem>) {
    trace!("print_suggest called with {} items", suggestions.len());
    let mut sorted_suggestions: Vec<SuggestItem> = suggestions.into_iter().collect();
    sorted_suggestions.sort();

    for suggest in sorted_suggestions {
        println!("{}", suggest.suggest());
    }
    std::process::exit(0);
}

fn print_suggest_with_description(suggestions: BTreeSet<SuggestItem>) {
    trace!(
        "print_suggest_with_description called with {} items",
        suggestions.len()
    );
    let mut sorted_suggestions: Vec<SuggestItem> = suggestions.into_iter().collect();
    sorted_suggestions.sort();

    for suggest in sorted_suggestions {
        match suggest.description() {
            Some(desc) => println!("{}$({})", suggest.suggest(), desc),
            None => println!("{}", suggest.suggest()),
        }
    }
    std::process::exit(0);
}

fn print_suggest_with_description_fish(suggestions: BTreeSet<SuggestItem>) {
    trace!(
        "print_suggest_with_description_fish called with {} items",
        suggestions.len()
    );
    let mut sorted_suggestions: Vec<SuggestItem> = suggestions.into_iter().collect();
    sorted_suggestions.sort();

    for suggest in sorted_suggestions {
        match suggest.description() {
            Some(desc) => println!("{}\t{}", suggest.suggest(), desc),
            None => println!("{}", suggest.suggest()),
        }
    }
    std::process::exit(0);
}

#[cfg(feature = "debug")]
fn trace_ctx(ctx: &ShellContext) {
    trace!("=== SHELL CTX BEGIN ===");
    trace!("command_line={}", ctx.command_line);
    trace!("cursor_position={}", ctx.cursor_position);
    trace!("current_word={}", ctx.current_word);
    trace!("previous_word={}", ctx.previous_word);
    trace!("command_name={}", ctx.command_name);
    trace!("word_index={}", ctx.word_index);
    trace!("all_words={:?}", ctx.all_words);
    trace!("shell_flag={:?}", ctx.shell_flag);
    trace!("===  SHELL CTX END  ===");
}

#[cfg(test)]
mod tests {
    use super::COMPLETION_SUBCOMMAND;

    #[test]
    fn completion_subcommand_constant() {
        assert_eq!(COMPLETION_SUBCOMMAND, "__comp");
    }
}
