[workspace]
resolver = "2"
members = [
    # Core
    "mingling",
    "mingling_core",
    "mingling_macros",

    # Pathfinder
    "mingling_pathf",
]

exclude = [
    # README-Tests
    "./temp/*",

    # Examples
    "examples/*",

    # Dev Tools
    ".run",

    # Tests
    "mingling_core/tests/*",
    "mingling_pathf/test"
]

[workspace.dependencies]
mingling_core = { path = "mingling_core", default-features = false }
mingling_macros = { path = "mingling_macros", default-features = false }
mingling_pathf = { path = "mingling_pathf", default-features = false }

arg-picker = { version = "0.2.0", default-features = false }
arg-picker-macros = { version = "0.2.0", default-features = false }

just_fmt = "0.2.1"
just_template = "0.2.1"
cargo_metadata = "0.23.1"

might_be_async = "0.1.0"

serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
toml = "1.1.4"
ron = "0.12.2"

dirs = "6.0.0"

syn = { version = "3.0.5", features = ["full", "visit-mut"] }
quote = "1.0.47"
proc-macro2 = "1.0.107"

colored = "3.1.1"
tokio = { version = "1", features = ["full"] }

log = "0.4.34"
env_logger = "0.11.11"

[workspace.package]
version = "0.5.0"
edition = "2024"
rust-version = "1.95.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mingling-rs/mingling"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[package]
name = "mingling-workspace"
version.workspace = true
edition.workspace = true
publish = false

[build-dependencies]
serde.workspace = true
serde_json.workspace = true
