[workspace]
resolver = "2"
members = ["mingling", "mingling_core", "mingling_macros", "mingling_pathf", "mling"]
exclude = [
    # README-Tests
    "./temp/*",

    # Examples
    "examples/*",

    # Dev Tools
    "dev_tools",

    # Tests
    "mingling_core/tests/*",
    "mingling_pathf/test"
]

[workspace.dependencies]
mingling_core = { version = "0.2.0", default-features = false }
mingling_macros = { version = "0.2.0", default-features = false }
mingling_pathf = { version = "0.2.0", default-features = false }

just_fmt = "0.1.2"
just_template = "0.2.0"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_yaml = "0.9.34"
toml = "1.1.2"
ron = "0.12.2"

dirs = "6.0.0"

syn = { version = "2.0.118", features = ["full", "visit-mut"] }
quote = "1.0.46"
proc-macro2 = "1.0.106"

colored = "3.1.1"
tokio = { version = "1", features = ["full"] }

log = "0.4.33"
env_logger = "0.11.11"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mingling-rs/mingling"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
