[package]
name = "example-clap-binding"
version = "0.1.0"
edition = "2024"

[dependencies.mingling]
path = "../../mingling"
# Enable `clap` features
features = ["clap"]

# Import `clap` to your project
[dependencies.clap]
version = "4.6.1"
features = [
    # Enable `derive` feature to support `clap::Parser`
    "derive",
    # Enable `color` feature to support ANSI colors
    "color",
]

[workspace]
