[package]
name = "arg-picker"
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mingling-rs/mingling/tree/main/arg_picker"
authors = ["Weicao-CatilGrass"]
readme = "README.md"
description = "A lightweight, type-safe CLI argument parser"

[features]
mingling_support = ["arg-picker-macros/mingling_support"]

[dependencies]
arg-picker-macros.workspace = true
just_fmt.workspace = true
