[package]
name = "example-async-support"
version = "0.1.0"
edition = "2024"

[dependencies.mingling]
path = "../../mingling"

# Enable `picker` features
features = ["async", "picker"]

# Import any async runtime, e.g. Tokio
[dependencies.tokio]
version = "1.52.3"
features = ["macros", "rt", "rt-multi-thread", "time"]

[workspace]
