[example]
id = "example-outside-type"
name = "Outside Type"
icon = "🆕"
category = "advanced"
desc = """
Demonstrates how to use the `group!()` macro to convert an external type into a type recognizable by Mingling
"""
tags = ["group!", "extras"]
files = ["src/main.rs", "Cargo.toml"]
