[[runs]]
input = [ "greet" ]

expect.exit-code = 0
expect.result = "Hello, World from mingling v0.5.0!"

[[runs]]
input = [ "greet", "Alice" ]

expect.exit-code = 0
expect.result = "Hello, Alice from mingling v0.5.0!"
