//! Configuration for the module pathfinder analysis.
//!
//! This module defines [`PathfinderConfig`], which controls behavior such as
//! whether dispatch-tree related types (`__internal_dispatcher_*`) should be
//! extracted.

/// Configuration for the module pathfinder analysis.
///
/// Controls behavior such as whether dispatch-tree related types
/// (`__internal_dispatcher_*`) should be extracted.
#[derive(Debug, Clone, Default)]
pub struct PathfinderConfig {
    /// Whether to also extract `__internal_dispatcher_*` static types
    /// generated by the `dispatch_tree` feature in Mingling.
    pub use_dispatch_tree: bool,
}

impl PathfinderConfig {
    /// Create a config with `use_dispatch_tree` enabled.
    #[must_use]
    pub const fn with_dispatch_tree() -> Self {
        Self {
            use_dispatch_tree: true,
        }
    }
}
