[package]
name = "mingling-cli"
version = "0.4.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mingling-rs/mingling/tree/main/mingling_cli"
authors = ["Weicao-CatilGrass"]
readme = "README.md"

description = "Mingling's scaffolding tool for generating, analyzing, and modifying Mingling projects"
keywords = ["cli", "cli-framework", "command-line", "tools"]
categories = ["command-line-interface"]

[[bin]]
name = "mling"
path = "src/bin/wrapper.rs"

[[bin]]
name = "mingling-cli"
path = "src/bin/cli.rs"

[dependencies.mingling]
path = "../mingling"
features = [
    "extras",
    "picker",
    "pathf",
    "dispatch_tree",
    "async",
    "comp",
]

[build-dependencies.mingling]
path = "../mingling"
features = [
    "build",
    "pathf",
    "dispatch_tree",
    "comp"
]

[dependencies]

# Project analyze
cargo_metadata = { version = "0.23.1", features = ["builder"] }
annotate-snippets = "0.12.16"

# Code analyze
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
syn = { version = "3.0.2", features = ["full", "extra-traits"] }
quote = "1.0.47"

# Configure & Serialization
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

# Parallelism
tokio = { version = "1.53.1", features = ["full"] }
toml_edit = "0.25.13"
colored = "3.1.1"
dirs = "6.0.0"
semver = "1.0.28"

# Code gen
just_template = "0.2.1"

# Template sources
sha2 = "0.10"

[build-dependencies]
# Configure & Serialization
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

# Code gen
just_template = "0.2.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[workspace]
