[package]
name = "mingling-cli"
version.workspace = true
edition.workspace = true
authors = ["Weicao-CatilGrass"]
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Mingling's scaffolding tool"
keywords = ["cli", "scaffolding", "command-line", "framework"]
categories = ["command-line-interface"]

[[bin]]
name = "cargo-mling"
path = "src/bin/cargo-mling.rs"

[[bin]]
name = "mling"
path = "src/bin/mling.rs"

[dependencies]
mingling = { path = "../mingling", features = [
    "parser",
    "comp",
    "structural_renderer",
    "extra_macros",
    "yaml_serde_fmt",
] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

colored = "3.1.1"
dirs = "6.0.0"
just_fmt = "0.1.2"
toml.workspace = true

[build-dependencies]
chrono = "0.4"
mingling = { path = "../mingling", features = ["comp", "builds"] }
