[package]
name = "arg-picker-macros"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mingling-rs/mingling/tree/main/arg_picker"
authors = ["Weicao-CatilGrass"]
readme = "README.md"
description = "Mingling's lightweight argument parser macros"

[lib]
proc-macro = true

[features]
mingling_support = []

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
