[package]
name = "mingling_picker_macros"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors = ["Weicao-CatilGrass"]
readme = "README.md"
description = "Mingling's lightweight argument parser macros"

[lib]
proc-macro = true

[features]
mingling_support = []

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
