[[file]]
file = "./Cargo.toml"
pattern = "version = \"{VER}\""

[[file]]
file = "./mingling_cli/Cargo.toml"
pattern = "version = \"{VER}\""

[[file]]
file = "./README.md"
pattern = "version = \"{VER}\""

[[file]]
file = "./docs/_zh_CN/pages/1-getting-started.md"
pattern = "version = \"{VER}\""

[[file]]
file = "./docs/pages/1-getting-started.md"
pattern = "version = \"{VER}\""

[[file]]
file = "./docs/res/guide.txt"
pattern = "mingling = \"{VER}\""

[[file]]
file = "./index.html"
pattern = "cargo add mingling@{VER}"

[[file]]
file = "./index.html"
pattern = "version = \"{VER}\""

[[file]]
file = "./index.html"
pattern = "mling proj-init {VER}@basic"
