[package]
name = "mingling"
version.workspace = true
edition.workspace = true
authors = ["Weicao-CatilGrass"]
license.workspace = true
readme = "README.md"
description = "A proc-macro and type-system based Rust CLI framework, suitable for complex CLI programs with numerous subcmds."
keywords = ["cli", "cli-framework", "subcommand", "macro", "command-line"]
categories = ["command-line-interface"]
repository.workspace = true

[dev-dependencies]
serde.workspace = true
tokio.workspace = true
mingling = { path = ".", features = [
    "comp",
    "structural_renderer",
    "repl",
] }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition", "--html-in-header", "arborium-header.html"]
features = [
    "docs_rs",
    "core",
    "macros",
    "builds",
    "structural_renderer",
    "repl",
    "comp",
    "picker",
    "clap",
    "extras",
]

[features]

# Presets
mini = ["extras", "picker"]
advanced = ["extras", "picker", "repl", "comp", "dispatch_tree", "structural_renderer"]
full = ["extras", "picker", "repl", "clap", "comp", "dispatch_tree", "structural_renderer_full", "pathf"]
build_advanced = ["build", "comp"]
build_full = ["build", "comp", "pathf", "dispatch_tree"]

# Core
core = ["dep:mingling_core", "mingling_core/default"]
macros = ["dep:mingling_macros", "mingling_macros/default"]

# Special features
nightly = ["mingling_core/nightly", "mingling_macros/nightly"]
debug = ["mingling_core/debug"]
async = ["mingling_core/async", "mingling_macros/async"]
default = ["core", "macros"]
build = ["mingling_core/build"]
# - Section only shown in docs.rs
docs_rs = []

# Features
clap = ["mingling_core/clap", "mingling_macros/clap"]
dispatch_tree = ["mingling_macros/dispatch_tree"]
repl = ["mingling_core/repl", "mingling_macros/repl"]
comp = ["mingling_core/comp", "mingling_macros/comp"]
picker = ["mingling_core/picker", "dep:arg-picker", "arg-picker/mingling_support"]
pathf = ["mingling_core/pathf", "mingling_macros/pathf"]

structural_renderer = [
    "mingling_core/structural_renderer",
    "dep:serde",
    "mingling_macros/structural_renderer",
    "json_serde_fmt",
]

structural_renderer_empty = [
    "mingling_core/structural_renderer",
    "dep:serde",
    "mingling_macros/structural_renderer",
]

structural_renderer_full = [
    "structural_renderer",
    "yaml_serde_fmt",
    "toml_serde_fmt",
    "ron_serde_fmt",
]

all_serde_fmt = [
    "json_serde_fmt",
    "yaml_serde_fmt",
    "toml_serde_fmt",
    "ron_serde_fmt",
]

json_serde_fmt = ["mingling_core/json_serde_fmt"]
yaml_serde_fmt = ["mingling_core/yaml_serde_fmt"]
toml_serde_fmt = ["mingling_core/toml_serde_fmt"]
ron_serde_fmt = ["mingling_core/ron_serde_fmt"]

extras = ["mingling_macros/extras"]

# - LEGACY -
# These are old names, will be Breaking Change in the future

builds = ["mingling_core/build"]
extra_macros = ["mingling_macros/extras"]

[dependencies]
mingling_core = { workspace = true, optional = true }
mingling_macros = { workspace = true, optional = true }
arg-picker = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
