[package]
name = "mingling"
version.workspace = true
edition.workspace = true
authors = ["Weicao-CatilGrass"]
license.workspace = true
readme = "README.md"
description = "A proc-macro and type-system based Rust CLI framework, suitable for complex CLI programs with numerous subcmds."
keywords = ["cli", "cli-framework", "subcommand", "macro", "command-line"]
categories = ["command-line-interface"]
repository.workspace = true

[dev-dependencies]
serde.workspace = true
tokio.workspace = true
mingling = { path = ".", features = [
    "comp",
    "structural_renderer",
    "parser",
    "repl",
] }

[package.metadata.docs.rs]
features = [
    "builds",
    "structural_renderer",
    "repl",
    "comp",
    "parser",
    "clap",
    "extra_macros",
]

[features]
nightly = ["mingling_core/nightly", "mingling_macros/nightly"]
debug = ["mingling_core/debug"]
async = ["mingling_core/async", "mingling_macros/async"]
builds = ["mingling_core/builds"]

default = ["mingling_core/default", "mingling_macros/default"]

clap = ["mingling_core/clap", "mingling_macros/clap"]
dispatch_tree = ["mingling_core/dispatch_tree", "mingling_macros/dispatch_tree"]
repl = ["mingling_core/repl", "mingling_macros/repl"]
comp = ["mingling_core/comp", "mingling_macros/comp"]
parser = ["dep:size"]
picker = ["dep:mingling_picker", "dep:mingling_picker_macros"]
pathf = ["mingling_core/pathf", "mingling_macros/pathf"]

structural_renderer = [
    "mingling_core/structural_renderer",
    "dep:serde",
    "mingling_macros/structural_renderer",
    "json_serde_fmt",
]

structural_renderer_empty = [
    "mingling_core/structural_renderer",
    "dep:serde",
    "mingling_macros/structural_renderer",
]

structural_renderer_full = [
    "structural_renderer",
    "yaml_serde_fmt",
    "toml_serde_fmt",
    "ron_serde_fmt",
]

all_serde_fmt = [
    "json_serde_fmt",
    "yaml_serde_fmt",
    "toml_serde_fmt",
    "ron_serde_fmt",
]

json_serde_fmt = ["mingling_core/json_serde_fmt"]
yaml_serde_fmt = ["mingling_core/yaml_serde_fmt"]
toml_serde_fmt = ["mingling_core/toml_serde_fmt"]
ron_serde_fmt = ["mingling_core/ron_serde_fmt"]

extra_macros = ["mingling_macros/extra_macros"]

[dependencies]
mingling_core.workspace = true
mingling_macros.workspace = true
mingling_picker = { workspace = true, optional = true }
mingling_picker_macros = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
size = { version = "0.5", optional = true }
