pub(crate) mod dispatcher;
pub(crate) mod empty_result;
pub(crate) mod entry;
pub(crate) mod gen_program;
pub(crate) mod import_type;
pub(crate) mod program_collect_gen;
#[cfg(feature = "comp")]
pub(crate) mod program_comp_gen;
pub(crate) mod program_fallback_gen;
pub(crate) mod r_append;
pub(crate) mod r_eprint;
pub(crate) mod r_eprintln;
pub(crate) mod r_print;
pub(crate) mod r_println;
pub(crate) mod register_chain;
pub(crate) mod register_dispatcher;
pub(crate) mod register_help;
pub(crate) mod register_metadata;
pub(crate) mod register_renderer;
pub(crate) mod register_type;
pub(crate) mod render_route;
pub(crate) mod route;
#[cfg(feature = "structural_renderer")]
pub(crate) mod structural;
#[cfg(feature = "comp")]
pub(crate) mod suggest;
#[cfg(feature = "comp")]
pub(crate) mod suggest_enum;
