pub(crate) mod dispatcher;
#[cfg(feature = "extras")]
pub(crate) mod empty_result;
#[cfg(feature = "extras")]
pub(crate) mod entry;
pub(crate) mod gen_program;
#[cfg(feature = "extras")]
pub(crate) mod group;
#[cfg(all(feature = "structural_renderer", feature = "extras"))]
pub(crate) mod group_structural;
pub(crate) mod node;
pub(crate) mod pack;
#[cfg(feature = "extras")]
pub(crate) mod pack_err;
#[cfg(all(feature = "structural_renderer", feature = "extras"))]
pub(crate) mod pack_err_structural;
#[cfg(feature = "structural_renderer")]
pub(crate) mod pack_structural;
#[cfg(feature = "comp")]
pub(crate) mod program_comp_gen;
pub(crate) mod program_fallback_gen;
pub(crate) mod program_final_gen;
pub(crate) mod r_append;
pub(crate) mod r_eprint;
pub(crate) mod r_eprintln;
pub(crate) mod r_print;
pub(crate) mod r_println;
pub(crate) mod register_chain;
pub(crate) mod register_dispatcher;
pub(crate) mod register_help;
pub(crate) mod register_renderer;
pub(crate) mod register_type;
#[cfg(feature = "extras")]
pub(crate) mod render_route;
#[cfg(feature = "extras")]
pub(crate) mod route;
#[cfg(feature = "comp")]
pub(crate) mod suggest;
#[cfg(feature = "comp")]
pub(crate) mod suggest_enum;
