[package]
name = "mingling_macros"
version.workspace = true
edition.workspace = true
authors = ["Weicao-CatilGrass"]
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Macros of the mingling library"
keywords = ["cli", "macros", "procedural", "command-line", "framework"]
categories = ["command-line-interface"]

[lib]
proc-macro = true

[features]
nightly = []
default = []
async = []

clap = []
comp = []
dispatch_tree = []
structural_renderer = []
repl = []
pathf = []

extras = []

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true

just_fmt.workspace = true
