name: CI (Check only)

on:
  push:
    branches-ignore: [main]
  pull_request:

jobs:
  Check-Codes:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Restore .temp cache
        id: cache-temp
        uses: actions/cache@v4
        with:
          path: .temp
          key: ${{ runner.os }}-mingling-temp-${{ hashFiles('Cargo.lock', 'dev_tools/Cargo.toml', 'verified-docs.toml', 'examples/test-examples.toml') }}-${{ hashFiles('dev_tools/src/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-mingling-temp-

      - run: cargo ci --test-codes

  Check-Docs:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Restore .temp cache
        id: cache-temp
        uses: actions/cache@v4
        with:
          path: .temp
          key: ${{ runner.os }}-mingling-temp-${{ hashFiles('Cargo.lock', 'dev_tools/Cargo.toml', 'verified-docs.toml', 'examples/test-examples.toml') }}-${{ hashFiles('dev_tools/src/**/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-mingling-temp-

      - run: cargo ci --test-docs
